# Configuration for the SigLIP 2 embedding generator

# Device to use: auto, cuda, cpu
device: auto

# Siglip 2 model to load from Hugging Face
# Example: google/google/siglip2-so400m-patch14-224
model_name: google/siglip2-base-patch16-naflex

# Server configuration
server_host: 0.0.0.0
server_port: 9000